### ISSUE TITLE
captions for images

### ISSUE THREAD

**Issue by rgcoe** [evergreen-innovations/sandia-fostwin-test-github-page#3]
In #2, one thing I noticed but did not address is that we currently have test for image captions that is written above the image command, e.g., 

```
Default Controller, note the inports on the left for real-time control coming from the web interface! 

![](images/default-ctrl.PNG)
```

Not sure if this is easily understood. Would be nice if `jekyll-theme-cayman` or whatever theme we land on has a better way to handle image captions.

**Comment by Graham-EGI** [comment]
Updated to use a table, with the following syntax:

```
| ![](images/default-ctrl.PNG) | 
| :--: |
| *Default Controller, note the inports on the left for real-time control coming from the web interface!* | 
```

I didn't see any other images with captions, please let me know if I missed any/ if I should add a quick caption for each image

**Comment by Graham-EGI** [comment]
Looks like this when deployed:

![image](https://user-images.githubusercontent.com/73138100/182651041-4662af37-006f-49c7-bca4-b945412c5d5f.png)

**Comment by rgcoe** [comment]
Love it!

**Comment by Graham-EGI** [comment]
Awesome! Closing
